export enum SettingsMutationTypes {
  SET_STATE = 'SET_STATE',
  // SET_TAGS_COLUMNS = 'SET_TAGS_COLUMNS',
  // SET_TAGS_ROWS = 'SET_TAGS_ROWS',
  // SET_MUSIC_VOLUME = 'SET_MUSIC_VOLUME',
  // SET_GAME_VOLUME = 'SET_GAME_VOLUME',
  SET_MUSIC_SELECTION = 'SET_MUSIC_SELECTION',
  SET_IMGS = 'SET_IMGS',
}
